name: deploy to kubernetes
on:
  registry_package:
    types: [published]

jobs:
  deploy:
    name: deploy to kube cluster
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - uses: Azure/k8s-deploy@v1.4
        with:
          namespace: 'default'
          manifests: kubernetes/deployment.yaml
          images: 'ghcr.io/eddiejaoude/stargate:v${{ steps.package-version.outputs.current-version}}'
          kubectl-version: 'latest'
