name: Import labels
on:
  push:
    branches:
      - eddiejaoude-issue-56

jobs:
  labels:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: checkout source files
        uses: actions/checkout@v2

      - name: use node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install deps
        run: npm ci

      - name: clear existing labels
        run: npx ghlbl -o eddiejaoude -r stargate -t ${{ secrets.GITHUB_TOKEN }} -d

      - name: import labels from json
        run: npx ghlbl -o eddiejaoude -r stargate -t ${{ secrets.GITHUB_TOKEN }} -i docs/labels.json
